# Server Configuration
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

# Spring Configuration
spring:

  #to enable colors when you run your app outside intellij
  output:
    ansi:
      enabled: always

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/taskflow?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
  liquibase:
    enabled: false
    change-log: db/master.xml
